name: Build Android APK

on:
  push:
    branches: [ main ]

env:
  BUILD_DIR: /home/runner/work/${{ github.repository }}/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          python3-pip autoconf libtool \
          pkg-config zlib1g-dev libncurses5-dev \
          libtinfo6 cmake libffi-dev libssl-dev \
          libxml2-dev libxslt-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade pip wheel
        pip install buildozer==1.5.0 cython==0.29.33

    - name: Initialize Buildozer environment
      run: |
        mkdir -p $BUILD_DIR/.buildozer/android/platform
        buildozer android update

    - name: Validate configuration
      run: |
        echo "=== buildozer.spec ==="
        cat buildozer.spec
        buildozer check

    - name: Build APK (with retry)
      run: |
        for i in {1..3}; do
          buildozer -v android clean && \
          buildozer -v android debug 2>&1 | tee build.log && \
          ([ -f bin/*.apk ] || (cat build.log && exit 1)) && break
          
          echo "Build attempt $i failed, retrying..."
          sleep 15
        done

    - name: Verify build artifacts
      run: |
        ls -lh .buildozer/android/platform/
        ls -lh bin/
        aapt dump badging bin/*.apk | grep package

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: comic-reader-apk
        path: bin/*.apk
        retention-days: 7
        if-no-files-found: error
